openapi: 3.0.3
info:
  title: Rampup Fraction Service - OpenAPI 3.0
  description: |-
    This is a sample Fraction Storage Server based on the OpenAPI 3.0 specification. 
  termsOfService: http://swagger.io/terms/
  contact:
    email: zjsnxc@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: localhost:3000/api
tags:
  - name: fraction
    description: Fraction, as defined in types.ts
paths:
  /fractions:
    post:
      tags:
        - fraction
      summary: Add a new Fraction to storage
      description: Add a new fraction to the storage
      operationId: addFraction
      requestBody:
        description: Create a new fraction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFractionDto'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fraction'          
        '405':
          description: Invalid input
    get:
      tags:
        - fraction
      summary: Find fractions
      operationId: getFractions
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fraction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Fraction record not found 
  /fractions/{fractionId}:
    get:
      tags:
        - fraction
      summary: Find fraction order by ID
      operationId: getFractionById
      parameters:
        - name: fractionId
          in: path
          description: ID of fraction that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fraction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Fraction record not found
components:
  schemas:
    CreateFractionDto:
      required:
        - numerator
        - denominator
      type: object
      properties:
        numerator:
          type: integer
          example: 1
        denominator:
          type: integer
          example: 2
    Fraction:
      required:
        - id
        - numerator
        - denominator
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        numerator:
          type: integer
          example: 1
        denominator:
          type: integer
          example: 2